export const UPDATE_FULL_SCREEN = 'UPDATE_FULL_SCREEN';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const ACTION_LOGIN = 'ACTION_LOGIN';

export const UPDATE_SHOW_TYPE = 'UPDATE_SHOW_TYPE';

export const CLEAR_ALL = 'CLEAR_ALL';

export const UPDATE_FOCUS_LIST = 'UPDATE_FOCUS_LIST';
export const ACTION_GET_FOCUS_LIST = 'ACTION_GET_FOCUS_LIST';
export const ACTION_FOCUS_ADD = 'ACTION_FOCUS_ADD';
export const ACTION_FOCUS_DELETE = 'ACTION_FOCUS_DELETE';
export const UPDATE_INCLUDE_ROUTES = 'UPDATE_INCLUDE_ROUTES';
